// This file is auto-generated by KSP. Do not edit manually.
import ExpressusComposables
import SwiftUI

public struct CoffeeSelectorsMobileRepresentable: UIViewControllerRepresentable {
    @Binding public var isMakingCoffee: Bool
    public let onAnyClick: () -> Void
    public let onSwiftUiClick: () -> Void
    public let onComposeClick: () -> Void

    public init(isMakingCoffee: Binding<Bool>, onAnyClick: @escaping () -> Void, onSwiftUiClick: @escaping () -> Void, onComposeClick: @escaping () -> Void) {
        _isMakingCoffee = isMakingCoffee
        self.onAnyClick = onAnyClick
        self.onSwiftUiClick = onSwiftUiClick
        self.onComposeClick = onComposeClick
    }

    public func makeUIViewController(context _: Context) -> UIViewController {
        CoffeeSelectorsMobileUIViewController().make(onAnyClick: onAnyClick, onSwiftUiClick: onSwiftUiClick, onComposeClick: onComposeClick)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        CoffeeSelectorsMobileUIViewController().update(isMakingCoffee: isMakingCoffee)
    }
}
