// This file is auto-generated by KSP. Do not edit manually.
import SwiftUI
import ExpressusComposables

public struct CoffeeSelectorsMobileRepresentable: UIViewControllerRepresentable {
    @Binding var isMakingCoffee: Bool
    let onAnyClick: () -> Void
    let onSwiftUiClick: () -> Void
    let onComposeClick: () -> Void

    public func makeUIViewController(context: Context) -> UIViewController {
        CoffeeSelectorsMobileUIViewController().make(onAnyClick: onAnyClick, onSwiftUiClick: onSwiftUiClick, onComposeClick: onComposeClick)
    }

    public func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        CoffeeSelectorsMobileUIViewController().update(isMakingCoffee: isMakingCoffee)
    }
}