// This file is auto-generated by KSP. Do not edit manually.
import ExpressusComposables
import SwiftUI

public struct CoffeeSelectorsMobileRepresentable: UIViewControllerRepresentable {
    @Binding var isMakingCoffee: Bool
    let onAnyClick: () -> Void
    let onSwiftUiClick: () -> Void
    let onComposeClick: () -> Void

    public func makeUIViewController(context _: Context) -> UIViewController {
        CoffeeSelectorsMobileUIViewController().make(onAnyClick: onAnyClick, onSwiftUiClick: onSwiftUiClick, onComposeClick: onComposeClick)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        CoffeeSelectorsMobileUIViewController().update(isMakingCoffee: isMakingCoffee)
    }
}
