// This file is auto-generated by KSP. Do not edit manually.
import ExpressusComposables
import SwiftUI

public struct ExpressusMobileRepresentable: UIViewControllerRepresentable {
    @Binding var state: ExpressusMobileState
    let makeCoffee: () -> Void

    public func makeUIViewController(context _: Context) -> UIViewController {
        ExpressusMobileUIViewController().make(makeCoffee: makeCoffee)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        ExpressusMobileUIViewController().update(state: state)
    }
}
