// This file is auto-generated by KSP. Do not edit manually.
import ExpressusComposables
import SwiftUI

public struct ExpressusMobileRepresentable: UIViewControllerRepresentable {
    @Binding public var state: ExpressusMobileState
    public let makeCoffee: () -> Void

    public init(state: Binding<ExpressusMobileState>, makeCoffee: @escaping () -> Void) {
        _state = state
        self.makeCoffee = makeCoffee
    }

    public func makeUIViewController(context _: Context) -> UIViewController {
        ExpressusMobileUIViewController().make(makeCoffee: makeCoffee)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        ExpressusMobileUIViewController().update(state: state)
    }
}
